### ISSUE TITLE
Just a thank you..

### ISSUE THREAD

**Issue by sdothum** [bclnr/kb-layout-evaluation#1]
i did a little write-up [here](http://thedarnedestthing.com/keyboard%20layout%20evaluation) using your kb evaluator with minor mods to add a thumb row so i could run it against my unorthodox BEAKL variants -- i believe the 4 additional lines plus config file changes accomplished what i wanted!

Just wanted to express my appreciation of your work.

If there are any corrections i should make to my blog entry regarding kb-layout-evaluation (misrepresentation, incorrect assumptions, etc.), please let me know, otherwise, please close this non-issue report!

**Comment by bclnr** [comment]
Thanks a lot for the write-up, I'm glad you found this little project useful. If you don't mind I'll link your post in the readme. 
It's quite interesting to see it extended to take thumb keys, and to see another take on penalties.

To be honest I initially developed this idea for my own curiosity, and didn't think it would be used by others. So I appreciate your feedback a lot.
