### ISSUE TITLE
Keyboard layout evaluation request : the-1

### ISSUE THREAD

**Issue by nicolasH** [bclnr/kb-layout-evaluation#2]
Hello

I came across this layout, it looks different from Colemak and puts the punctuation on the center columns instead of the outer columns, as well as arrange the marks differently. It says it favors splats instead of alternating hands.

Any chance you could evaluate it? I am also looking at writing English (mostly), French (sometimes) and Spanish (rarely)

https://docs.google.com/document/d/1yiCnIi1oagV1D8ZouMt-TRFRG8d6AfSBIwQkBvSflvY/edit
Photo of the original document:

![the-1-keyboard-layout](https://user-images.githubusercontent.com/21255/101671843-5a818180-3a55-11eb-8dec-706406e6ab22.png)

**Comment by bclnr** [comment]
Done. It ranks pretty well, except in French where it's more average.
Thanks for finding that one.
