### ISSUE TITLE
BEAKL 19bis

### ISSUE THREAD

**Issue by hasufell** [bclnr/kb-layout-evaluation#4]
Where is it from?

https://github.com/bclnr/kb-layout-evaluation/blob/724df31d3cba07eaf05ab35127e027b46468dc99/layout_evaluation/config.txt#L204

The link leads to a reddit thread that doesn't show much info on it or who authored it.

**Comment by bclnr** [comment]
I have no idea. That's the only source I could find.
I only added it after it was mentioned on that thread, and surprisingly it gave very good results.

Unfortunately the website that hosted most of the info and discussions around "BEAKL" variants is down ( https://ieants.cc/ ). The only sources I can find on those efforts are http://thedarnedestthing.com/ and https://deskthority.net/wiki/BEAKL , but they don't seem to contain that particular layout.

**Comment by bclnr** [comment]
If anyone has more information, or more similar layouts that are worth evaluating, please feel free to post.

**Comment by sunaku** [comment]
**_Update:_** Upon RTFM, I now understand that it's an unused key with a default French character. :sweat_smile: 

What is the second `é` character (between apostrophe and period) on the left-hand bottom row?

```
# q y o u z w d n c k #
- h i e a , g t r s p ;
è j ' é . x v m l f b #
```

Is it supposed to be a `/` slash? because that's the only other character that seems to be missing.

**Comment by bclnr** [comment]
Right, it's an unused key. 
And since I'm particularly interested in typing French, I put the "é" on there to get better results. If you don't care about French you can ignore it or replace it with whatever character you want.

Maybe including French characters on unused keys is misleading for other people though. Not sure what to do about it.

**Comment by sunaku** [comment]
I think that is fine since it's explained in the README. :+1:  I have another question: what is the significance of `bis`?

The original Reddit post doesn't mention it, so I wonder what it means and whether it's an official BEAKL variant.

**Comment by bclnr** [comment]
Not, it's not an official BEAKL variant. 
The Reddit thread I linked gave a variant of BEAKL 19 saying "a new layout with identical configuration rules as BEAKL 19, but where the letters 'EAT' are preset to specific keys". So I understand the person just generated a layout and didn't give it a name. 
That's also why it was really unexpected for me to see it perform so well.

I just called it "bis" to say it's a variant of it. It means "twice" in latin I think: it's used in some places to designate a second thing with the same name, like 2 buildings with the same address.

**Comment by iandoug** [comment]
> I have no idea. That's the only source I could find.
> I only added it after it was mentioned on that thread, and surprisingly it gave very good results.
> 
> Unfortunately the website that hosted most of the info and discussions around "BEAKL" variants is down ( https://ieants.cc/ ). The only sources I can find on those efforts are http://thedarnedestthing.com/ and https://deskthority.net/wiki/BEAKL , but they don't seem to contain that particular layout.

Den has disappeared.
His repo is at https://bitbucket.org/Shenafu/keyboard-layout-analyzer/src/master/

I've put a mirror of his KLATest at https://klatest.keyboard-design.com/#/main ... it has the other variants he made. That 19bis is not included .. I didn't see it before here. Besides we tended to focus on English mainly.

Cheers, Ian
