### ISSUE TITLE
uciea

### ISSUE THREAD

**Issue by iandoug** [bclnr/kb-layout-evaluation#8]
Hi

Just curious as to how these do. uciea is mine, the other is by Steven Tammen
	
.Both were developed around (English) bigrams....

Thanks. Ian

![optimal-digram en ansi](https://user-images.githubusercontent.com/12673886/116465158-258f9300-a86d-11eb-8576-9a6f162909ad.jpg)
![uciea-keyboard en ansi](https://user-images.githubusercontent.com/12673886/116465197-33451880-a86d-11eb-980d-c66d11feae5b.jpg)

**Comment by bclnr** [comment]
Hello, thanks for the suggestion, I can add them easily. However it's not clear what they should be called.
I understand they are on https://keyboard-design.com/internet-letter-layout-db.html
Could you provide the url and names for them? I can't find them.

**Comment by iandoug** [comment]
The names are on each board. You can use the part before .en.ansi.

https://keyboard-design.com/letterlayout.html?layout=optimal-digram.en.ansi
https://keyboard-design.com/letterlayout.html?layout=uciea-keyboard.en.ansi

**Comment by bclnr** [comment]
My bad I missed it in the pictures. Thanks.
